{
 "title": "Bookie Metrics",
 "description": "Metrics of bookkeeper cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cloud_streamnative_io_cluster=~\".+\"}"
    }
   },
   {
    "name": "pod",
    "label": "Bookie",
    "query": "bookkeeper_server_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Writable Bookies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(bookie_SERVER_STATUS{cloud_streamnative_io_cluster=~\"$cluster\"} == 1)\n   "
    }
   ]
  },
  {
   "title": "ReadOnly Bookies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(bookie_SERVER_STATUS{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"} == 0)\n"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "description": "success rate for different types of requests",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum(irate(bookkeeper_server_ADD_ENTRY_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m])) / sum(irate(bookkeeper_server_ADD_ENTRY_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "add_entry"
    },
    {
     "expr": "100 * sum(irate(bookkeeper_server_READ_ENTRY_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m])) / sum(irate(bookkeeper_server_READ_ENTRY_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "read_entry"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.99\"})",
     "legendFormat": "add (p99)"
    },
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.999\"})",
     "legendFormat": "add (p999)"
    },
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.5\"})",
     "legendFormat": "add (p50)"
    },
    {
     "expr": "avg(bookkeeper_server_READ_ENTRY_REQUEST{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.99\"})",
     "legendFormat": "read (p99)"
    },
    {
     "expr": "avg(bookkeeper_server_READ_ENTRY_REQUEST{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.999\"})",
     "legendFormat": "read (p999)"
    },
    {
     "expr": "avg(bookkeeper_server_READ_ENTRY_REQUEST{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.5\"})",
     "legendFormat": "read (p50)"
    }
   ]
  },
  {
   "title": "writable bookies (percentage)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 \n* \ncount(bookie_SERVER_STATUS{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"} == 1)\n/\ncount(bookie_SERVER_STATUS{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"})\n   "
    }
   ]
  },
  {
   "title": "Throughput (MB / s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bookie_WRITE_BYTES{cloud_streamnative_io_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "add entry"
    },
    {
     "expr": "sum(rate(bookie_READ_BYTES{cloud_streamnative_io_cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "read entry"
    }
   ]
  },
  {
   "title": "Entry Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m]))",
     "legendFormat": "read entry"
    },
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m]))",
     "legendFormat": "add entry"
    }
   ]
  },
  {
   "title": "Ledgers Disk Usage (Persistent Volume Metrics)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\".*ledgers.*\"} /    kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*ledgers.*\"}))",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Journal Disk Usage (Persistent Volume Metrics)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\".*journal.*\"} /    kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*journal.*\"}))",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Ledgers Disk Usage (Bookie Metric)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_ledger_dir__pulsar_data_bookkeeper_ledgers_0_usage{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_WRITE_BYTES{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Read Bytes (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_READ_BYTES{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Add Entry Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Read Entry Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_REQUEST_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "ADD_ENTRY (Inprogress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY_IN_PROGRESS{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "READ_ENTRY (Inprogress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_IN_PROGRESS{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "ADD_ENTRY (Blocked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY_BLOCKED{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "READ_ENTRY (Blocked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_BLOCKED{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Add entry latency (p50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.5\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Add entry latency (99pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.99\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Add entry latency (p999)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.999\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Read entry latency (p50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_REQUEST{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.5\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Read entry latency (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_REQUEST{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.99\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Read entry latency (p999)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_REQUEST{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.999\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Journal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Journal Sync Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_journal_JOURNAL_SYNC_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_journal_JOURNAL_ADD_ENTRY_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_QUEUE_SIZE{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Force Write Queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_FORCE_WRITE_QUEUE_SIZE{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Callback Queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_journal_JOURNAL_CB_QUEUE_SIZE{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"} [5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Add latency (p50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.5\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Add latency (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.99\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Add latency (Max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_ADD_ENTRY{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"1.0\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency (p50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_SYNC{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.5\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_SYNC{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"0.99\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_SYNC{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\", quantile=\"1.0\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ledgers count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_ledgers_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Entries count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_entries_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Write Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_write_cache_size{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_read_cache_size{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read entry rate from read cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_read_cache_hits_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read entry rate cache misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_read_cache_misses_count{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deleted Ledger Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_DELETED_LEDGER_COUNT{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Writable Ledger Directory Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_ledger_writable_dirs{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_MAJOR_COMPACTION_COUNT{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "major compaction - {{pod}}"
    },
    {
     "expr": "sum(bookie_MINOR_COMPACTION_COUNT{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "minor compaction - {{pod}}"
    }
   ]
  },
  {
   "title": "GC Reclaim Disk (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bookie_RECLAIMED_COMPACTION_SPACE_BYTES{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "compaction - {{pod}}"
    },
    {
     "expr": "sum(rate(bookie_RECLAIMED_DELETION_SPACE_BYTES{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "deletion - {{pod}}"
    }
   ]
  }
 ]
}