{
 "title": "Containers Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(up{}, namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{cloud_streamnative_io_component=~\"broker|proxy|bookie|zookeeper|recovery|function|sink|source\", namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pod",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum( rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum( rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum( rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace!~\"kube-system\", pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{namespace!~\"kube-system\", pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace!~\"kube-system\", pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{namespace!~\"kube-system\", pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum( rate(container_network_receive_bytes_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{namespace!~\"kube-system\",pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  }
 ]
}