{
 "title": "JVM Metrics",
 "description": "JVM Related Metrics",
 "tags": [ "jvm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cluster=~\".+\"}"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": "jvm_memory_bytes_used{cloud_streamnative_io_component=~\".+\"}"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "jvm_memory_bytes_used{cluster=~\"$cluster\",cloud_streamnative_io_component=~\"$component\", pod=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "$job - $kubernetes_pod_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "kubernetes_pod_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{pod=~\"$pod\"}[30s]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{pod=~\"$pod\"})",
     "legendFormat": "Heap size"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{pod=~\"$pod\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{pod=~\"$pod\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes_used{pod=~\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_direct_bytes_max{pod=~\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{pod=~\"$pod\"}[30s]))",
     "legendFormat": "Pause"
    }
   ]
  }
 ]
}