{
 "title": "Auto Recovery Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cluster=~\".+\"}"
    }
   },
   {
    "name": "pod",
    "label": "Bookie Recovery",
    "query": "replication_worker_NUM_BYTES_READ_count{cluster=~\"$cluster\", pod=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Under-Replicated Ledgers count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(auditor_NUM_UNDER_REPLICATED_LEDGERS_count{cluster=~\"$cluster\", success=\"true\"})",
     "legendFormat": "$cluster"
    }
   ]
  },
  {
   "title": "Replication read throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_BYTES_READ_sum{cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replication read entry rate (entries/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_ENTRIES_READ{cluster=~\"$cluster\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replication write throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_BYTES_WRITTEN_sum{cluster=~\"$cluster\", pod=~\"$pod\", success=\"true\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replication write entry rate (entries/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_ENTRIES_WRITTEN{cluster=~\"$cluster\", pod=~\"$pod\"}[5m])",
     "legendFormat": "$cluster"
    }
   ]
  }
 ]
}