{
 "title": "Pulsar - Transaction",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cloud_streamnative_io_cluster=~\".+\"}"
    }
   },
   {
    "name": "coordinator_id",
    "label": "CoordinatorId",
    "query": {
     "query": "pulsar_txn_committed_count{cloud_streamnative_io_cluster=~\"$cluster\", coordinator_id=~\".+\", }"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Created Txn Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_txn_created_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"})"
    }
   ]
  },
  {
   "title": "Active Txn",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_txn_active_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"})"
    }
   ]
  },
  {
   "title": "Committed Txn Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_txn_committed_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"})"
    }
   ]
  },
  {
   "title": "Timeout Txn Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_txn_timeout_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"})"
    }
   ]
  },
  {
   "title": "Aborted Txn Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_txn_aborted_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"})"
    }
   ]
  },
  {
   "title": "Created Txn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "irate(pulsar_txn_created_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}[1m])",
     "legendFormat": "{{cluster}} - {{coordinator_id}}"
    }
   ]
  },
  {
   "title": "Commit Txn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "irate(pulsar_txn_committed_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}[1m])",
     "legendFormat": "{{cluster}} - {{coordinator_id}}"
    }
   ]
  },
  {
   "title": "Aborted Txn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(pulsar_txn_aborted_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}[1m])",
     "legendFormat": "{{cluster}} - {{coordinator_id}}"
    }
   ]
  },
  {
   "title": "Timeout Txn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "irate(pulsar_txn_timeout_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}[1m])",
     "legendFormat": "{{cluster}} - {{coordinator_id}}"
    }
   ]
  },
  {
   "title": "Append Txn Log rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "irate(pulsar_txn_append_log_count{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}[1m])",
     "legendFormat": "{{cluster}} - {{coordinator_id}}"
    }
   ]
  },
  {
   "title": "Txn Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(pulsar_txn_execution_latency_le_10{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "0 - 10 ms"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_20{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_50{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "20 - 50ms"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_100{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_500{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "100 - 500ms"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_1000{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "500 - 1000 ms"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_5000{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "1 - 5 s"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_15000{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "5 - 15 s"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_30000{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "15 - 30 s"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_60000{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "30 - 60 s"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_300000{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "1 - 5 m"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_1500000{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "5 - 25 m"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_1500000{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "25 - 50 m"
    },
    {
     "expr": "sum(pulsar_txn_execution_latency_le_overflow{cloud_streamnative_io_cluster=~\"$cluster\", job=~\".*broker\", coordinator_id=~\"$coordinator_id\"}) / 60.0",
     "legendFormat": "> 50 m"
    }
   ]
  }
 ]
}