{
 "title": "AXE Metricsㅓㅓ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Endpoint - all_tcp_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(all_tcp_connections_total{service=\"endpoint\"})"
    }
   ]
  },
  {
   "title": "Endpoint - current_tcp_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(current_tcp_connections{service=\"endpoint\"})"
    }
   ]
  },
  {
   "title": "Endpoint - socket_to_hc_producer_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(socket_to_hc_producer_latency_bucket{service=\"endpoint\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "  sum(socket_to_hc_producer_latency_bucket{service=\"endpoint\", le=\"5.0\"})",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "  sum(socket_to_hc_producer_latency_bucket{service=\"endpoint\", le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "  sum(socket_to_hc_producer_latency_bucket{service=\"endpoint\", le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "  sum(socket_to_hc_producer_latency_bucket{service=\"endpoint\", le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "  sum(socket_to_hc_producer_latency_bucket{service=\"endpoint\", le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  },
  {
   "title": "Endpoint - socket_to_manager_producer_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(socket_to_manager_producer_latency_bucket{service=\"endpoint\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "sum(socket_to_manager_producer_latency_bucket{service=\"endpoint\", le=\"5.0\"})",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "sum(socket_to_manager_producer_latency_bucket{service=\"endpoint\", le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "sum(socket_to_manager_producer_latency_bucket{service=\"endpoint\", le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "sum(socket_to_manager_producer_latency_bucket{service=\"endpoint\", le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "sum(socket_to_manager_producer_latency_bucket{service=\"endpoint\", le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  },
  {
   "title": "Endpoint - pulsar_to_socket_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(pulsar_to_socket_latency_bucket{service=\"endpoint\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "  sum(pulsar_to_socket_latency_bucket{service=\"endpoint\", le=\"5.0\"})",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "  sum(pulsar_to_socket_latency_bucket{service=\"endpoint\", le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "  sum(pulsar_to_socket_latency_bucket{service=\"endpoint\", le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "  sum(pulsar_to_socket_latency_bucket{service=\"endpoint\", le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "  sum(pulsar_to_socket_latency_bucket{service=\"endpoint\", le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  },
  {
   "title": "Health Checker - available_job_loop",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(available_job_loop_total{service=\"healthchecker\"})"
    }
   ]
  },
  {
   "title": "Health Checker - job_finish_latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job_finish_latency_bucket{service=\"healthchecker\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "sum(job_finish_latency_bucket{service=\"healthchecker\",le=\"5.0\"}) by",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "sum(job_finish_latency_bucket{service=\"healthchecker\",le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "sum(job_finish_latency_bucket{service=\"healthchecker\",le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "sum(job_finish_latency_bucket{service=\"healthchecker\",le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "sum(job_finish_latency_bucket{service=\"healthchecker\",le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  },
  {
   "title": "Manager - grpc init",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(init_sent_count_total{service=\"manager\"})",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(init_received_count_total{service=\"manager\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(init_success_count_total{service=\"manager\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(init_fail_count_total{service=\"manager\"})",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "Manager - grpc inference",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inference_sent_count_total{service=\"manager\"})",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(inference_received_count_total{service=\"manager\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(inference_success_count_total{service=\"manager\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(inference_fail_count_total{service=\"manager\"})",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "Manager - inference_init_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inference_init_latency_bucket{service=\"manager\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "  sum(inference_init_latency_bucket{service=\"manager\", le=\"5.0\"})",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "  sum(inference_init_latency_bucket{service=\"manager\", le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "  sum(inference_init_latency_bucket{service=\"manager\", le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "  sum(inference_init_latency_bucket{service=\"manager\", le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "  sum(inference_init_latency_bucket{service=\"manager\", le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  },
  {
   "title": "Manager - inference_finish_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(inference_finish_latency_bucket{service=\"manager\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "  sum(inference_finish_latency_bucket{service=\"manager\", le=\"5.0\"})",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "  sum(inference_finish_latency_bucket{service=\"manager\", le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "  sum(inference_finish_latency_bucket{service=\"manager\", le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "  sum(inference_finish_latency_bucket{service=\"manager\", le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "  sum(inference_finish_latency_bucket{service=\"manager\", le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  },
  {
   "title": "Manager - inference_inference_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(inference_inference_latency_bucket{service=\"manager\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "  sum(inference_inference_latency_bucket{service=\"manager\", le=\"5.0\"})",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "  sum(inference_inference_latency_bucket{service=\"manager\", le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "  sum(inference_inference_latency_bucket{service=\"manager\", le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "  sum(inference_inference_latency_bucket{service=\"manager\", le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "  sum(inference_inference_latency_bucket{service=\"manager\", le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  },
  {
   "title": "Inference - pyinferencer_create",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pyinferencer_create_total{service=\"inference\"}) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Inference - pyinferencer_create_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(pyinferencer_create_latency_bucket{service=\"inference\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "  sum(pyinferencer_create_latency_bucket{service=\"inference\", le=\"5.0\"})",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "  sum(pyinferencer_create_latency_bucket{service=\"inference\", le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "  sum(pyinferencer_create_latency_bucket{service=\"inference\", le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "  sum(pyinferencer_create_latency_bucket{service=\"inference\", le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "  sum(pyinferencer_create_latency_bucket{service=\"inference\", le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  },
  {
   "title": "Inference - grpc_init",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_init_received_total{service=\"inference\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(grpc_init_response_total{service=\"inference\"})",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "Inference - grpc_inference",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_inference_received_total{service=\"inference\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(grpc_inference_response_total{service=\"inference\"})",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "Inference - grpc_init_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(grpc_init_latency_bucket{service=\"inference\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "  sum(grpc_init_latency_bucket{service=\"inference\", le=\"5.0\"})",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "  sum(grpc_init_latency_bucket{service=\"inference\", le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "  sum(grpc_init_latency_bucket{service=\"inference\", le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "  sum(grpc_init_latency_bucket{service=\"inference\", le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "  sum(grpc_init_latency_bucket{service=\"inference\", le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  },
  {
   "title": "Inference - grpc_inference_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(grpc_inference_latency_bucket{service=\"inference\", le=\"1.0\"})",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "  sum(grpc_inference_latency_bucket{service=\"inference\", le=\"5.0\"})",
     "legendFormat": "< 5ms"
    },
    {
     "expr": "  sum(grpc_inference_latency_bucket{service=\"inference\", le=\"10.0\"})",
     "legendFormat": "< 10ms"
    },
    {
     "expr": "  sum(grpc_inference_latency_bucket{service=\"inference\", le=\"20.0\"})",
     "legendFormat": "< 20ms"
    },
    {
     "expr": "  sum(grpc_inference_latency_bucket{service=\"inference\", le=\"100.0\"})",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "  sum(grpc_inference_latency_bucket{service=\"inference\", le=\"+Inf\"})",
     "legendFormat": "< +Inf"
    }
   ]
  }
 ]
}