{
 "title": "Bookie Metrics",
 "description": "Metrics of bookkeeper cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "bookkeeper_server_ADD_ENTRY{job=~\".+\"}"
   },
   {
    "name": "kubernetes_pod_name",
    "label": "Bookie",
    "query": "bookkeeper_server_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\".+\"}"
   }
  ]
 },
 "panels": [
  { "title": "Healthy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Writable Bookies",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(bookie_SERVER_STATUS{job=~\"$job\"} == 1)\n   "
    }
   ]
  },
  {
   "title": "ReadOnly Bookies",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(bookie_SERVER_STATUS{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} == 0)\n"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "description": "success rate for different types of requests",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum(irate(bookkeeper_server_ADD_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\"}[30s])) / sum(irate(bookkeeper_server_ADD_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s]))",
     "legendFormat": "add_entry"
    },
    {
     "expr": "100 * sum(irate(bookkeeper_server_READ_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\"}[30s])) / sum(irate(bookkeeper_server_READ_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s]))",
     "legendFormat": "read_entry"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.99\"})",
     "legendFormat": "add (p99)"
    },
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.999\"})",
     "legendFormat": "add (p999)"
    },
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.5\"})",
     "legendFormat": "add (p50)"
    },
    {
     "expr": "avg(bookkeeper_server_READ_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.99\"})",
     "legendFormat": "read (p99)"
    },
    {
     "expr": "avg(bookkeeper_server_READ_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.999\"})",
     "legendFormat": "read (p999)"
    },
    {
     "expr": "avg(bookkeeper_server_READ_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.5\"})",
     "legendFormat": "read (p50)"
    }
   ]
  },
  {
   "title": "writable bookies (percentage)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 \n* \ncount(bookie_SERVER_STATUS{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} == 1)\n/\ncount(bookie_SERVER_STATUS{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})\n   "
    }
   ]
  },
  {
   "title": "Throughput (MB / s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bookie_WRITE_BYTES{job=~\"$job\"}[30s]))",
     "legendFormat": "add entry"
    },
    {
     "expr": "sum(rate(bookie_READ_BYTES{job=~\"$job\"}[30s]))",
     "legendFormat": "read entry"
    }
   ]
  },
  {
   "title": "Entry Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\"}[30s]))",
     "legendFormat": "read entry"
    },
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\"}[30s]))",
     "legendFormat": "add entry"
    }
   ]
  },
  {
   "title": "Ledgers Disk Usage (Persistent Volume Metrics)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\".*bookie-ledgers.*\"} /    kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*bookie-ledgers.*\"}))",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Journal Disk Usage (Persistent Volume Metrics)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\".*bookie-journal.*\"} /    kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*bookie-journal.*\"}))",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Ledgers Disk Usage (Bookie Metric)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_ledger_dir__pulsar_data_bookkeeper_ledgers_usage{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Write Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_WRITE_BYTES{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Read Bytes (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_READ_BYTES{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Add Entry Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_REQUEST_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Read Entry Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_REQUEST_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "ADD_ENTRY (Inprogress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY_IN_PROGRESS{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "READ_ENTRY (Inprogress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_IN_PROGRESS{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "ADD_ENTRY (Blocked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY_BLOCKED{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "READ_ENTRY (Blocked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_BLOCKED{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Add entry latency (p50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Add entry latency (99pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Add entry latency (p999)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.999\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Read entry latency (p50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Read entry latency (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Read entry latency (p999)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY_REQUEST{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.999\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Journal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Journal Sync Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_journal_JOURNAL_SYNC_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_journal_JOURNAL_ADD_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_QUEUE_SIZE{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Force Write Queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_FORCE_WRITE_QUEUE_SIZE{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Callback Queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_CB_QUEUE_SIZE{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Add latency (p50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Add latency (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Add latency (Max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"1.0\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency (p50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_SYNC{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_SYNC{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_SYNC{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", quantile=\"1.0\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Ledgers count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_ledgers_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Entries count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_entries_count{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Write Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_write_cache_size{job=~\"$job\", kubernetes_pod_name=~\"$$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Read Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_read_cache_size{job=~\"$job\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Read entry rate from read cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_read_cache_hits_count{job=~\"$job\", kubernetes_pod_name=~\"$$kubernetes_pod_name\", success=\"true\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Read entry rate cache misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bookie_read_cache_misses_count{job=~\"$job\", kubernetes_pod_name=~\"$$kubernetes_pod_name\", success=\"true\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Deleted Ledger Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_DELETED_LEDGER_COUNT{job=~\"$job\", kubernetes_pod_name=~\"$$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Writable Ledger Directory Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_ledger_writable_dirs{job=~\"$job\", kubernetes_pod_name=~\"$$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bookie_MAJOR_COMPACTION_COUNT{job=~\"$job\", kubernetes_pod_name=~\"$$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "major compaction - {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(bookie_MINOR_COMPACTION_COUNT{job=~\"$job\", kubernetes_pod_name=~\"$$kubernetes_pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "minor compaction - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Reclaim Disk (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bookie_RECLAIMED_COMPACTION_SPACE_BYTES{job=~\"$job\", kubernetes_pod_name=~\"$$kubernetes_pod_name\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "compaction - {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(bookie_RECLAIMED_DELETION_SPACE_BYTES{job=~\"$job\", kubernetes_pod_name=~\"$$kubernetes_pod_name\"}[30s])) by (kubernetes_pod_name)",
     "legendFormat": "deletion - {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}