{
 "title": "Compaction Service",
 "description": "Ursa compaction service metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "poolmember", "label": "poolmember", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "kubernetes_namespace",
    "query": {
     "query": "label_values(target_info,kubernetes_namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(target_info,cloud_streamnative_io_cluster)"
    }
   },
   {
    "name": "broker",
    "label": "broker",
    "query": {
     "query": "label_values(target_info{cloud_streamnative_io_component=\"compaction-scheduler\"},job)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(pulsar_storage_compact_lag{cloud_streamnative_io_component=\"compaction-scheduler\"},topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topic",
   "type": "stat",
   "description": "Ongoing compaction topic count",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_compact_ongoing_topic_count{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "stat",
   "description": "Ongoing compaction task count",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pulsar_storage_compact_ongoing_task_count{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish Failed Tasks",
   "type": "stat",
   "description": "Publish failed tasks count",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "pulsar_storage_compact_publish_task_failed_count_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compact Failed Tasks",
   "type": "stat",
   "description": "Compact failed tasks count",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_compact_failed_task_count_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Failed Tasks",
   "type": "stat",
   "description": "Compact failed tasks count",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_compact_task_commit_duration_seconds_count{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", ponse_status=\"failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit parquet files batch count",
   "type": "stat",
   "description": "Ongoing compaction task count",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pulsar_storage_compact_commit_task_batch_size{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compaction Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Topic compaction lag (Ursa)",
     "type": "timeseries",
     "description": "The lag of task published offset and task committed offset",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "pulsar_storage_compact_latest_published_offset{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"} - pulsar_storage_compact_last_compacted_offset{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Topic compaction lag (Pulsar)",
     "type": "timeseries",
     "description": "The lag of task published offset and task committed offset",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "topk(10, pulsar_subscription_back_log{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", subscription=\"__OFFLOAD\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Topic task publish lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "pulsar_storage_compact_latest_message_offset{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"} - pulsar_storage_compact_latest_published_offset{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"} + 1",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Compaction Task Stats",
     "type": "timeseries",
     "description": "The lag of task published offset and task committed offset",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "avg(pulsar_storage_compact_tasks_in_init_state{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
       "legendFormat": "INIT"
      },
      {
       "expr": "avg(pulsar_storage_compact_tasks_in_compacted_state{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
       "legendFormat": "COMPACTED"
      },
      {
       "expr": "avg(pulsar_storage_compact_tasks_in_prepared_commit_state{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
       "legendFormat": "PREPARE_COMMIT"
      },
      {
       "expr": "avg(pulsar_storage_compact_tasks_in_committe_state{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
       "legendFormat": "COMMITTED"
      }
     ]
    },
    {
     "title": "Non Committable Task Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"10.0\"}",
       "legendFormat": "0-10"
      },
      {
       "expr": "pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"50.0\"} - pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"10.0\"}",
       "legendFormat": "10 - 50"
      },
      {
       "expr": "pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"100.0\"} - pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"50.0\"}",
       "legendFormat": "50 - 100"
      },
      {
       "expr": "pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"200.0\"} - pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"100.0\"}",
       "legendFormat": "100 - 200"
      },
      {
       "expr": "pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"300.0\"} - pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"200.0\"}",
       "legendFormat": "200 - 300"
      },
      {
       "expr": "pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"400.0\"} - pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"300.0\"}",
       "legendFormat": "300 - 400"
      },
      {
       "expr": "pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"500.0\"} - pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"400.0\"}",
       "legendFormat": "400 - 500"
      },
      {
       "expr": "pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"1000.0\"} - pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"500.0\"}",
       "legendFormat": "500 - 1000"
      },
      {
       "expr": "pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"+Inf\"} - pulsar_storage_compact_non_committable_task_histogram_bytes_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", le=\"100.0\"}",
       "legendFormat": "> 1000"
      }
     ]
    },
    {
     "title": "Non Committable Tasks by Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pulsar_storage_compact_non_committable_task_count{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Compaction throughput In Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_compact_bytes_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})[30s])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Compaction Messages Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_compact_messages_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})[30s])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Bytes Size of each published task",
     "type": "timeseries",
     "description": "Each published task batched message bytes size",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pulsar_storage_compact_published_task_bytes{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Committed Parquet file Bytes",
     "type": "timeseries",
     "description": "The committed parquet file bytes size",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pulsar_storage_compact_committed_parquet_file_bytes{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"}",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Compaction Duration for one task (p50)",
     "type": "timeseries",
     "description": "One published task compact duration",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_compact_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Compaction Duration for one task (p99)",
     "type": "timeseries",
     "description": "One published task compact duration",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_compact_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Compaction Duration for one task (max)",
     "type": "timeseries",
     "description": "One published task compact duration",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_compact_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Messages From WAL Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_compact_read_messages_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Messages From WAL Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_compact_read_messages_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Messages From WAL Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_compact_read_messages_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Write Messages to Parquet Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_compact_write_messages_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Write Messages to Parquet Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_compact_write_messages_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Write Messages to Parquet Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_compact_write_messages_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Task Commit Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_compact_task_commit_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Task Commit Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_compact_task_commit_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Task Commit Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_compact_task_commit_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Commit Snapshot to Lakehouse Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_compact_commit_to_lakehouse_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Commit Snapshot to Lakehouse Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_compact_commit_to_lakehouse_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Commit Snapshot to Lakehouse Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_compact_commit_to_lakehouse_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message from Ursa to Parquet Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_compact_message_from_ursa_to_parquet_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message from Ursa to Parquet Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_compact_message_from_ursa_to_parquet_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message from Ursa to Parquet Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_compact_message_from_ursa_to_parquet_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message from ursa to Lakehouse Latency (p50)",
     "type": "timeseries",
     "description": "Message from goes into Ursa topic to available in Lakehouse Latency",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_compact_message_end_to_end_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message from ursa to lakehouse Latency (p99)",
     "type": "timeseries",
     "description": "Message from goes into Ursa topic to available in Lakehouse Latency",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_compact_message_end_to_end_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message from ursa to lakehouse Latency (max)",
     "type": "timeseries",
     "description": "Message from goes into Ursa topic to available in Lakehouse Latency",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_compact_message_end_to_end_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistent API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Throughput In Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1029 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_read_entry_size_bytes_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})[30s])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Messages Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1029 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_read_entry_count_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})[30s])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Index and data Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1037 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_read_entry_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Index and data Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1037 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_read_entry_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Index and data Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1037 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_read_entry_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Message Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1045 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_read_entries_data_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Message Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1045 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_read_entries_data_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Message Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1045 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_read_entries_data_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Index From Oxia Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1053 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_read_entries_index_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Index From Oxia Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1053 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_read_entries_index_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Index From Oxia Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1053 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_read_entries_index_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Entry Metadata From Oxia Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1061 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_read_entrymetadata_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Entry Metadata From Oxia Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1061 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_read_entrymetadata_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Entry Metadata From Oxia Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1061 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_read_entrymetadata_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Cache Eviction Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1030 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_wal_readCache_eviction_count_ratio_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})[30s])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Cache Loading Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1030 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_wal_readCache_loading_count_ratio_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})[30s])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Entry From WAL (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1038 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_wal_getEntries_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Entry From WAL (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1038 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_wal_getEntries_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Entry From WAL (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1038 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_wal_getEntries_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Cache Loading data From S3 Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1046 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_wal_readCache_loading_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Cache Loading data From S3 Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1046 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_wal_readCache_loading_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Cache Loading data From S3 Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1046 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_wal_readCache_loading_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Read Throughput In Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1031 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_backend_read_bytes_count_bytes_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})[30s])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read request from S3 Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1031 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_backend_storage_request_total{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})[30s])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Message From S3 Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1039 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_backend_read_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Message From S3 Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1039 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_backend_read_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Read Message From S3 Latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1039 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le) (pulsar_storage_backend_read_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Bytes from Lakehouse",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1032 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_lakehouse_read_bytes_total{kubernetes_namespace=\"$kubernetes_namespace\"})) by (kubernetes_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read Messages from Lakehouse",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1032 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(pulsar_storage_lakehouse_read_messages_total{kubernetes_namespace=\"$kubernetes_namespace\"})) by (kubernetes_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read Messages from Lakehouse Latency (p50)",
     "type": "timeseries",
     "description": "Read Messages from Lakehouse Latency",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1040 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le, kubernetes_pod_name) (pulsar_storage_lakehouse_read_latency_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", pulsar_response_status=\"success\"}))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Read Messages from Lakehouse Latency (p99)",
     "type": "timeseries",
     "description": "Read Messages from Lakehouse Latency",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1040 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le, kubernetes_pod_name) (pulsar_storage_lakehouse_read_latency_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", pulsar_response_status=\"success\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read Messages from Lakehouse Latency (max)",
     "type": "timeseries",
     "description": "Read Messages from Lakehouse Latency",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1040 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by (le, kubernetes_pod_name) (pulsar_storage_lakehouse_read_latency_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", pulsar_response_status=\"success\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction Write in Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lakehouse Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 564 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_lakehouse_writer_write_all_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_lakehouse_writer_write_all_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (pulsar_storage_lakehouse_writer_write_all_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Lakehouse Encode Record Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 572 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_lakehouse_writer_encode_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_lakehouse_writer_encode_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (pulsar_storage_lakehouse_writer_encode_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Lakehouse Before Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 572 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_lakehouse_writer_before_write_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_lakehouse_writer_before_write_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (pulsar_storage_lakehouse_writer_before_write_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Lakehouse Write Record Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 572 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_lakehouse_writer_write_record_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_lakehouse_writer_write_record_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (pulsar_storage_lakehouse_writer_write_record_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Parquet Write Record Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 580 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_lakehouse_parquet_write_record_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_lakehouse_parquet_write_record_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (pulsar_storage_lakehouse_parquet_write_record_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Parquet Write Metadata Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 580 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (pulsar_storage_lakehouse_parquet_write_metadata_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (pulsar_storage_lakehouse_parquet_write_metadata_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (pulsar_storage_lakehouse_parquet_write_metadata_duration_seconds_bucket{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", cloud_streamnative_io_component=\"compaction-scheduler\", pulsar_response_status=\"success\"}))",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "DLQ Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compaction Task Stats",
     "type": "timeseries",
     "description": "The lag of task published offset and task committed offset",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 468 },
     "targets": [
      {
       "expr": "avg(pulsar_storage_compact_topics_in_dlq{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
       "legendFormat": "Topics In DLQ"
      },
      {
       "expr": "avg(pulsar_storage_compact_tasks_in_dlq{kubernetes_namespace=\"$kubernetes_namespace\", cloud_streamnative_io_cluster=\"$cluster\", job=~\"$broker\"})",
       "legendFormat": "Tasks In DLQ"
      }
     ]
    }
   ]
  }
 ]
}