{
 "title": "Containers Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{app=~\".*\"}, app)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(up{app=~\"$cluster\"}, kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\", container!=\"\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\", container!=\"\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\", container!=\"\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\", container!=\"\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\", container!=\"\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\", container!=\"\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\", container!=\"\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\", container!=\"\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\", container!=\"\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\", container!=\"\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\", container!=\"\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 50 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 71 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 78 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 85 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 85 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 92 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 92 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 99 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 99 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 106 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 106 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 113 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 113 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 120 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 120 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 127 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 127 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)\n",
     "legendFormat": "system"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 134 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{pod=~\"$pod\"}) by (pod_name)",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 134 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (pod_name,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  }
 ]
}