{
 "title": "Inference",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Inf latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(inference_actor_to_data_store_inf_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(data_store_loop_to_pulsar_broker_get_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(pulsar_loop_to_inf_loop_end_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(inf_loop_to_bridge_inference_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(bridge_to_inf_loop_inf_result_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    },
    {
     "expr": "sum(data_store_to_grpc_inference_latency_bucket{service=\"inference\", le=\"+Inf\"})"
    }
   ]
  },
  {
   "title": "Inf Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"1.0\"})"
    },
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"5.0\"})"
    },
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"10.0\"})"
    },
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"100.0\"})"
    },
    {
     "expr": "sum(grpc_inference_latency_bucket{service=\"inference\",le=\"+Inf\"})"
    }
   ]
  },
  {
   "title": "Average",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(grpc_inference_latency_sum[1m]) /rate(grpc_inference_latency_count[1m])) / count(grpc_inference_latency_count)"
    },
    {
     "expr": "sum(rate(inference_actor_to_data_store_inf_latency_sum[1m]) /rate(inference_actor_to_data_store_inf_latency_count[1m])) / count(inference_actor_to_data_store_inf_latency_count)"
    },
    {
     "expr": "sum(rate(data_store_loop_to_pulsar_broker_get_latency_sum[1m]) /rate(data_store_loop_to_pulsar_broker_get_latency_count[1m])) / count(data_store_loop_to_pulsar_broker_get_latency_count)"
    },
    {
     "expr": "sum(rate(pulsar_loop_to_inf_loop_end_latency_sum[1m]) /rate(pulsar_loop_to_inf_loop_end_latency_count[1m])) / count(pulsar_loop_to_inf_loop_end_latency_count)"
    },
    {
     "expr": "sum(rate(inf_loop_to_bridge_inference_latency_sum[1m]) /rate(inf_loop_to_bridge_inference_latency_count[1m])) / count(inf_loop_to_bridge_inference_latency_count)"
    },
    {
     "expr": "sum(rate(bridge_to_inf_loop_inf_result_latency_sum[1m]) /rate(bridge_to_inf_loop_inf_result_latency_count[1m])) / count(bridge_to_inf_loop_inf_result_latency_count)"
    },
    {
     "expr": "sum(rate(data_store_to_grpc_inference_latency_sum[1m]) /rate(data_store_to_grpc_inference_latency_count[1m])) / count(data_store_to_grpc_inference_latency_count)"
    }
   ]
  }
 ]
}