{
 "title": "Overview",
 "description": "Overview of Pulsar Cluster",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(up{job=\"zookeeper\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Bookies",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(up{job=\"bookie\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(up{job=\"broker\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(up{job=\"proxy\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pulsar_storage_size) by (cluster)"
    }
   ]
  },
  {
   "title": "Backlog",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog) by (cluster)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * ( 1 - \n   ( sum(increase(node_cpu_seconds_total{mode=\"idle\"}[1m]))\n    / \n   sum(increase(node_cpu_seconds_total[1m]))\n  )\n)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Zookeeper Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * count(up{job=\"zookeeper\"} == 1) / count(up{job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "Bookies Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * count(up{job=\"bookie\"} == 1) / count(up{job=\"bookie\"})"
    }
   ]
  },
  {
   "title": "Brokers Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * count(up{job=\"broker\"} == 1) / count(up{job=\"broker\"})"
    }
   ]
  },
  {
   "title": "Proxies Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * count(up{job=\"proxy\"} == 1) / count(up{job=\"proxy\"})"
    }
   ]
  },
  { "title": "Messaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Messaging Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_size) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Message Rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_in) by (cluster)",
     "legendFormat": "{{ cluster }} - In"
    },
    {
     "expr": "sum(pulsar_rate_out) by (cluster)",
     "legendFormat": "{{ cluster }} - Out"
    }
   ]
  },
  {
   "title": "Top 10  topics backlog",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_msg_backlog) by (topic))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Messaging Backlog",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_in) by (cluster)",
     "legendFormat": "{{ cluster }} - In"
    },
    {
     "expr": "sum(pulsar_throughput_out) by (cluster)",
     "legendFormat": "{{ cluster }} - Out"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (1 - (sum(increase(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance)\n/ \nsum(increase(node_cpu_seconds_total[1m])) by (instance)))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100 ",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}